spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    generate-unique-name: false
    hikari:
      maximum-pool-size: 4
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: 127.0.0.1
    port: 13004
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
kakao:
  api:
    url: https://dapi.kakao.com
    uri: /v2/search/blog
    key: c883282f9e6b6474d9cbfff7745e91cb
naver:
  api:
    url: https://openapi.naver.com
    uri: /v1/search/blog.json
    secret: Gtoa3aaKLf
    id: QkcW870ApambkXZb4khf